[profile.default]
solc = '0.8.4'
src = 'src'
out = 'out'
libs = ['lib']

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
base-sepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

